"use client";

import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import ViewListIcon from "@mui/icons-material/ViewList";
import Form from "../../components/form-contact";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="full-screen h-screen grid grid-rows-template grid-cols-4 gap-6 place-content-center">
        <div className="col-start-2 col-span-2 flex flex-row justify-end">
          <Link
            href="/contact"
            className="text-md text-center text-white bg-indigo-500 hover:bg-indigo-700 hover:shadow-xl p-1 rounded-full size-10 text-center shadow-md"
          >
            <ViewListIcon />
          </Link>
        </div>
        <div className="col-start-2 col-span-2 md:h-[60vh]">
          <Form />
        </div>
      </main>
    </div>
  );
};

export default Home;
